- tests/parser/dsl_parser/test_DSLparser.py
- tests/parser/dsl_parser/test_ast.py
- tests/parser/dsl_parser/test_token.py
- tests/parser/test_ParserFactory.py
- tests/parser/test_YAMLParser.py
- tests/parser/test_parsedfile.py
- tests/repository/test_github_repository.py
- tests/repository/test_local_repository.py
- tests/repository/test_resourcemodel.py
- tests/test_e2e.py
- thipster/engine/engine.py
- thipster/engine/parsed_file.py
- thipster/engine/resource_model.py
- thipster/parser/dsl_parser/ast.py
- thipster/parser/dsl_parser/exceptions.py
- thipster/parser/dsl_parser/interpreter.py
- thipster/parser/dsl_parser/parser.py
- thipster/parser/dsl_parser/token.py
- thipster/parser/dsl_parser/token_parser.py
- thipster/repository/json.py
- thipster/terraform/cdk.py
for dsl nodes, parsed file and resource model classes :
- removes useless properties
- applies pep8 naming to variables
adds a position attibute to every dsl node
closes #146
> :art: fix: improve dsl's ast code

- .github/ISSUE_TEMPLATE/doc_update.yml
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- CONTRIBUTING.md
- README.md
- setup.py
Add a pull request template, update setup.py and README.md
Fixes #151
> :memo: fix(doc): Update repository and package documentation

- tests/engine/test_generation.py
- tests/resources/e2e/models/network.json
- tests/test_e2e.py
- thipster/parser/yaml_parser.py
- thipster/terraform/cdk.py
Closes #102 
wrote a test to pass the spec example
> :sparkles: feat: allow resource creation from dependency

- thipster/terraform/cdk.py
- thipster/terraform/exceptions.py
missing attribute error was not helpful
Ran against current tests
> :goal_net: fix: improve missing attribute error

- thipster/terraform/cdk.py
Allow default optional values to be none
ran all present tests
> :bug: fix: allow None in default optional values

- .gitignore
- tests/resources/e2e/models/backend_service.json
- tests/resources/e2e/models/bucket.json
- thipster/terraform/cdk.py
Removes duplicated code in cdk file
Check if all non-optional internal objects have a value
ran on all current tests
> :bug: fix: non optional internal objects

- thipster/terraform/cdk.py
Fix a bug with created resources
Ran current tests
> :bug: fix: created resources list

- thipster/terraform/cdk.py
Name was set to 'name' when provided via attribute
ran against current tests
> :bug: fix: correct name when provided via attribute

- tests/engine/test_engine.py
- thipster/engine/engine.py
- thipster/terraform/cdk.py
Add an auto apply when calling the THipster engine apply method
Fixes #170 
- Executed the demo script with and without the apply method
> :sparkles: feat: add tf auto apply

- thipster/terraform/cdk.py
Add possibility to choose an argument other than id when using an explicted dependency
ran on current tests
> :sparkles: feat: add option to choose explicit dep arg

- thipster/terraform/cdk.py
Remove comma typo from https://github.com/THipster/THipster/pull/182#discussion_r1239393959
Ran current tests
> :art: fix: remove comma

- thipster/terraform/cdk.py
Fixes issues with resource creation from dependency:
- set resource_name
- add it to explicit dependencies list
> :bug: fix: set name + add to created resources

- thipster/terraform/cdk.py
Fix support for list dependencies
> :bug: fix: list dependencies

- .github/labeler.yml
- .github/pull_request_template.md
- .github/workflows/codeql.yml
- .github/workflows/pr-handler.yml
- .readthedocs.yaml
- README.md
- docs/source/index.rst
Update the ci/cd pipeline to match Thipster-cli
:memo: Documentation update
> :green_heart: fix: update ci and doc

- tests/repository/test_github_repository.py
- thipster/repository/github.py
- thipster/terraform/cdk.py
Update GHRepo to comply with CLI
Related to THipster/models#6
> :bug: fix: update githubrepo with folder_name

- thipster/engine/parsed_file.py
- thipster/terraform/cdk.py
Add a property to convert parsed values to python built-ins
> :bug: fix: unmarshalled parsed values

- tests/parser/dsl_parser/test_dslparser.py
- tests/parser/dsl_parser/test_lexer.py
- thipster/parser/dsl_parser/grammar.ebnf
- thipster/parser/dsl_parser/interpreter.py
- thipster/parser/dsl_parser/lexer.py
- thipster/parser/dsl_parser/lexer_position.py
- thipster/parser/dsl_parser/token.py
- thipster/parser/dsl_parser/token_parser.py
Add a few sytax points to the dsl
see #61
> :sparkles: feat: upgrade dsl

- thipster/parser/dsl_parser/token_parser.py
Add variables as atoms to arithmetic expressions
> :bug: fix: add variable to arithmetic expr

- .github/workflows/pr-handler.yml
Remove edit trigger to pr handler
Fixes #197
> :green_heart: fix: remove edit to pr handler

- tests/engine/test_generation.py
- tests/parser/dsl_parser/test_dslparser.py
- tests/parser/dsl_parser/test_lexer.py
- thipster/parser/dsl_parser/grammar.ebnf
- thipster/parser/dsl_parser/lexer.py
- thipster/parser/dsl_parser/token_parser.py
Add Dict in DSL lists
Add YAML -like indentation to DSL lists
Fixes #194 
> :sparkles: feat: dict in dsl list

- tests/parser/dsl_parser/test_ast.py
- tests/parser/dsl_parser/test_dslparser.py
- thipster/parser/dsl_parser/ast.py
- thipster/parser/dsl_parser/grammar.ebnf
- thipster/parser/dsl_parser/interpreter.py
- thipster/parser/dsl_parser/lexer.py
- thipster/parser/dsl_parser/token_parser.py
Add option to define variables 
Add an end delimiter when using variables in string
Closes #195 
> :sparkles: feat: variable definition

- tests/engine/test_engine.py
- tests/test_e2e.py
- tests/test_tools.py
- thipster/engine/engine.py
- thipster/engine/i_terraform.py
- thipster/helpers.py
- thipster/terraform/cdk.py
Fix the typo in the 'terraform apply' command, use the various terraform included in thipster in the e2e tests.
> :bug: fix(terraform): fix terraform apply command and add test

- .github/workflows/release.yml
> :green_heart: fix(): actions versions

- tests/parser/dsl_parser/test_dslparser.py
- thipster/parser/dsl_parser/grammar.ebnf
- thipster/parser/dsl_parser/token_parser.py
rename according to grammar.ebnf
> :recycle: refactor: use correct functions + rename according to grammar

- .github/workflows/stale-issue-pr-closer.yml
Disable stale issues since the ones open today will probably still be open in 8 month
> :green_heart: feat: disable stale issues

- .github/workflows/pr-handler.yml
- README.md
- pipelines/automated_tests.py
- requirements/requirements-test.txt
Add tests coverage status report available at https://coveralls.io/github/THipster/THipster.
Please delete options that are not relevant.
:green_heart: Change to the CI pipeline
:memo: Documentation update
> :green_heart: feat(ci): Add coverage status report

- tests/engine/test_engine.py
- thipster/engine/engine.py
- thipster/engine/exceptions.py
Use the engine properties, check type when setting port implementations
> :recycle: fix: use engine properties

- tests/parser/dsl_parser/test_dslparser.py
- tests/parser/dsl_parser/test_lexer.py
- thipster/parser/dsl_parser/lexer.py
- thipster/parser/dsl_parser/token_parser.py
When parsing DSL:
Removed the newline that was added at the end of files since it is not useful anymore
Added to option to check for a list of tokens
Fixed an issue where multiple whitespaces between words would not parse
> :bug: fix: allow unusual spacing + remove eof newline

- .github/workflows/pr-handler.yml
- pipelines/automated_tests.py
Add env variables to enable coveralls to identify the execution environment, branch, build number and pull-request number.
Modify the forgotten dagger version in the pre-commit run reserved for docs updates.
Tested on dagger locally using the main branch to update the coveralls report.
> :bug: fix(ci): Add missing coveralls parameters hidden by dagger

- requirements.txt
Remove python-terraform as it was remplaced by syscalls
> :heavy_minus_sign: fix: remove python-terraform

- tests/engine/test_parsedfile.py
- tests/engine/test_resourcemodel.py
- thipster/engine/parsed_file.py
- thipster/engine/resource_model.py
Adds tests for our generators
Moves our classes test files to an appropriate location
:white_check_mark: Test stuff
> :white_check_mark: feat: add tests for generators

- tests/parser/dsl_parser/test_lexer.py
- thipster/parser/dsl_parser/lexer.py
- thipster/parser/dsl_parser/lexer_position.py
Clean the character escaping
Add test
Add escaped newline to output string
> :recycle: refactor: clean character escaping

- tests/repository/test_github_repository.py
Change THipster/models branch used in tests
This will allow us to easily update the THipster/models repository
> :white_check_mark: feat: change GitHub tests branch
